//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.15 at 08:28:48 PM GET 
//


package com.cookbook.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cookbook.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cookbook.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cookbook }
     * 
     */
    public Cookbook createCookbook() {
        return new Cookbook();
    }

    /**
     * Create an instance of {@link Cookbook.Recipe }
     * 
     */
    public Cookbook.Recipe createCookbookRecipe() {
        return new Cookbook.Recipe();
    }

    /**
     * Create an instance of {@link Cookbook.Recipe.Ingredient }
     * 
     */
    public Cookbook.Recipe.Ingredient createCookbookRecipeIngredient() {
        return new Cookbook.Recipe.Ingredient();
    }

    /**
     * Create an instance of {@link Cookbook.Recipe.Time }
     * 
     */
    public Cookbook.Recipe.Time createCookbookRecipeTime() {
        return new Cookbook.Recipe.Time();
    }

    /**
     * Create an instance of {@link Cookbook.Recipe.Method }
     * 
     */
    public Cookbook.Recipe.Method createCookbookRecipeMethod() {
        return new Cookbook.Recipe.Method();
    }

}
